### ISSUE TITLE
I hope you to add declare file

### ISSUE THREAD

**Issue by dulee-dev** [harshmangalam/qwik-lottie-web#1]
`
declare module 'qwik-lottie-web' {
  import * as QwikLottiWeb from 'qwik-lottie-web';
  interface QwikLottie {
    container: HTMLElement;
    animationData: JSON;
  }
  export const QwikLottie: JSX<QwikLottie>;
}
`

thanks I become real fan of you ^_^

**Comment by harshmangalam** [comment]
Thanks dulle fixed the type issues
